import { getImagePath } from "./image-helper";

export const metamorfose = [
  {
    imageSrc: getImagePath("Untitled1.jpeg"),
    Untitled: "Untitled 1",
    title: "Acrílica sobre Tela, 2022-24",
    size: "1.0 x 1.00 m",
    description: "Moldura branca tipo filete",
    price: "R$ 3.250,00",
  },
  {
    imageSrc: getImagePath("Untitled2.jpeg"),
    Untitled: "Untitled 2",
    title: "Acrílica sobre Tela, 2018-24",
    size: "1.0 x 1.00 m",
    description: "Moldura branca tipo filete",
    price: "R$ 3.250,00",
  },
];

export const untitled = [
  {
    Untitled: "Untitled I",
    imageSrc: getImagePath("UntitledI.jpeg"),
    size: "1.20 x 0.20 m",
    title: "Acrílica sobre 6 Telas, 2023-24",
    description: "Chassis duplo, tipo painel",
    price: "R$ 780,00",
  },
];

export const deusAtomo = [
  {
    Untitled: "Untitled 3",
    imageSrc: getImagePath("Untitled3.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2023",
    description: "Chassis duplo, tipo painel",
    price: "R$ 975,00",
  },
  {
    Untitled: "Untitled 4",
    imageSrc: getImagePath("Untitled4.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Óleo sobre Tela, 2024",
    description: "Chassis duplo, tipo painel",
    price: "R$ 975,00",
  },
  {
    Untitled: "Untitled 5",
    imageSrc: getImagePath("Untitled5.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2024",
    description: "Chassis duplo, tipo painel",
    price: "R$ 975,00",
  },
  {
    Untitled: "Untitled 6",
    imageSrc: getImagePath("Untitled6.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2023",
    description: "Chassis duplo, tipo painel",
    price: "R$ 600,00",
  },
  {
    Untitled: "Untitled 7",
    imageSrc: getImagePath("Untitled7.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2022-24",
    description: "Chassis duplo, tipo painel",
    price: "R$ 975,00",
  },
  {
    Untitled: "Untitled 8",
    imageSrc: getImagePath("Untitled8.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2023",
    description: "Chassis duplo, tipo painel",
    price: "R$ 975,00",
  },
  {
    Untitled: "Untitled 9",
    imageSrc: getImagePath("Untitled9.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2023",
    description: "Chassis duplo, tipo painel",
    price: "R$ 600,00",
  },
  {
    Untitled: "Untitled 10",
    imageSrc: getImagePath("Untitled10.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Óleo sobre Tela, 2024",
    description: "Chassis duplo, tipo painel",
    price: "R$ 975,00",
  },
];

export const transmutacao = [
  {
    Untitled: "Untitled 11",
    imageSrc: getImagePath("Untitled11.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2024",
    description: "Chassis duplo, tipo painel",
    price: "R$ 1.200,00",
  },
  {
    Untitled: "Untitled 12",
    imageSrc: getImagePath("Untitled12.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Óleo sobre Tela, 2024",
    description: "Chassis duplo, tipo painel",
    price: "R$ 1.200,00",
  },
  {
    Untitled: "Untitled 13",
    imageSrc: getImagePath("Untitled13.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2024",
    description: "Chassis duplo, tipo painel",
    price: "R$ 1.200,00",
  },
  {
    Untitled: "Untitled 14",
    imageSrc: getImagePath("Untitled14.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2024",
    description: "Chassis duplo, tipo painel",
    price: "R$ 1.200,00",
  },
  {
    Untitled: "Untitled 15",
    imageSrc: getImagePath("Untitled15.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2024",
    description: "Chassis duplo, tipo painel",
    price: "R$ 1.200,00",
  },
  {
    Untitled: "Untitled 16",
    imageSrc: getImagePath("Untitled16.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2024",
    description: "Chassis duplo, tipo painel",
    price: "R$ 1.200,00",
  },
  {
    Untitled: "Untitled 17",
    imageSrc: getImagePath("Untitled17.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2023-24",
    description: "Chassis duplo, tipo painel",
    price: "R$ 1.200,00",
  },
  {
    Untitled: "Untitled 18",
    imageSrc: getImagePath("Untitled18.jpeg"),
    size: " 0.60 x 0.50 m",
    title: "Óleo sobre Tela, 2023-24",
    description: "Chassis duplo, tipo painel",
    price: "R$ 1.200,00",
  },
];

export const acervo = [
  {
    Untitled: "Untitled II",
    imageSrc: getImagePath("UntitledII.jpeg"),
    size: "0.60 x 0.50 m",
    title: "Óleo sobre Tela, 2024",
    description: "Chassis duplo, tipo painel",
    price: "R$ 1.200,00",
  },
  {
    Untitled: "Untitled III",
    imageSrc: getImagePath("UntitledIII.jpeg"),
    size: "0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2023",
    description: "Chassis duplo, tipo painel",
    price: "R$ 600,00",
  },
  {
    Untitled: "Untitled IV",
    imageSrc: getImagePath("UntitledIV.jpeg"),
    size: "0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2023",
    description: "",
    price: "R$ 400,00",
  },
  {
    Untitled: "Untitled V",
    imageSrc: getImagePath("UntitledV.jpeg"),
    size: "0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2023",
    description: "",
    price: "R$ 400,00",
  },
  {
    Untitled: "Untitled VI",
    imageSrc: getImagePath("UntitledVI.jpeg"),
    size: "0.60 x 0.50 m",
    title: "Acrílica sobre Tela, 2023",
    description: "",
    price: "R$ 400,00",
  },
  {
    Untitled: "Untitled VII",
    imageSrc: getImagePath("UntitledVII.jpeg"),
    size: "1.40 x 1.40 m",
    title: "Acrílica sobre Lona, 2016-2023",
    description: "Painel",
    price: "R$ 4.550,00",
  },
  {
    Untitled: "Untitled VIII",
    imageSrc: getImagePath("UntitledVIII.jpeg"),
    size: "1.00 x 1.00 m",
    title: "Acrílica sobre Tela, 2022",
    description: "Moldura branca tipo filete",
    price: "R$ 2.000,00",
  },
  {
    Untitled: "Untitled IX",
    imageSrc: getImagePath("UntitledIX.jpeg"),
    size: "1.50 x 0.86 m",
    title: "Acrílica sobre Lona, 2016-2022",
    description: "Painel, Moldura branca tipo filete",
    price: "R$ 4.190,00",
  },
  {
    Untitled: "Untitled X",
    imageSrc: getImagePath("UntitledX.jpeg"),
    size: "1.00 x 1.00 m",
    title: "Acrílica sobre Tela, 2022",
    description: "Moldura branca tipo filete",
    price: "R$ 2.000,00",
  },
  {
    Untitled: "Untitled XI",
    imageSrc: getImagePath("UntitledXI.jpeg"),
    size: "1.42 x 1.00 m",
    title: "Pigmento, PVA, Acrílica, Carvão e Grafite sobre Lona, 2016-2023",
    description: "Painel",
    price: "R$ 2.840,00",
  },
  {
    Untitled: "Untitled XII",
    imageSrc: getImagePath("UntitledXII.jpeg"),
    size: "1.50 x 1.06 m",
    title: "Pigmento, PVA, Acrílica e Carvão sobre Lona, 2016-2022",
    description: "Painel com moldura branca tipo filete",
    price: "R$ 3.018,00",
  },
  {
    Untitled: "Untitled XIII",
    imageSrc: getImagePath("UntitledXIII.jpeg"),
    size: "1.42 x 1.00 m",
    title: "Pigmento, Acrílica e Óleo sobre Lona, 2017-2018",
    description: "Painel",
    price: "R$ 2.840,00",
  },
  {
    Untitled: "Untitled XIV",
    imageSrc: getImagePath("UntitledXIV.jpeg"),
    size: "0.64 x 0.47 m",
    title: "Acrílica sobre Madeira com Chassi, 2020",
    description: "",
    price: "R$ 400,00",
  },
];
